#!/usr/bin/env python

print('''
*******************************************************************************
          |                   |                  |                     |
 _________|________________.=""_;=.______________|_____________________|_______
|                   |  ,-"_,=""     `"=.|                  |
|___________________|__"=._o`"-._        `"=.______________|___________________
          |                `"=._o`"=._      _`"=._                     |
 _________|_____________________:=._o "=._."_.-="'"=.__________________|_______
|                   |    __.--" , ; `"=._o." ,-"""-._ ".   |
|___________________|_._"  ,. .` ` `` ,  `"-._"-._   ". '__|___________________
          |           |o`"=._` , "` `; .". ,  "-._"-._; ;              |
 _________|___________| ;`-.o`"=._; ." ` '`."\` . "-._ /_______________|_______
|                   | |o;    `"-.o`"=._``  '` " ,__.--o;   |
|___________________|_| ;     (#) `-.o `"=.`_.--"_o.-; ;___|___________________
____/______/______/___|o;._    "      `".o|o_.--"    ;o;____/______/______/____
/______/______/______/_"=._o--._        ; | ;        ; ;/______/______/______/_
____/______/______/______/__"=._o--._   ;o|o;     _._;o;____/______/______/____
/______/______/______/______/____"=._o._; | ;_.--"o.--"_/______/______/______/_
____/______/______/______/______/_____"=.o|o_.--""___/______/______/______/____
/______/______/______/______/______/______/______/______/______/______/_____ /
*******************************************************************************
''')

print("Welcome to Robs Tr3a5ur3_15land")
print("Your Quest is to find the hidden treasure")
direction1 = input("You come to a fork in the road. Do you turn (Left) or (Right)? ").lower()
if direction1 == "left":
    direction2 = input("You come across a raaging river, do you go over the (Bridge) or try to (Swim)? ").lower()
    if direction2 == "swim":
        direction3 = input("You power your way through the river and stumpble across 3 doors.\nWhich one will you choose. (Red), (Blue) or (Green)? ").lower()
        if direction3 == "green":
            print("CONGATS, you found the treasure!")
        elif direction3 == "red":
            print("You spontainiously set on fire and DIE!")
        elif direction3 == "blue":
            print("I don't know, something else kills you...... you decide. \nTry to be creative :)")
    else:
        print("You are attacked by bridge fairing, killer trout (Bet you didn't see that one coming), You DIE!!")
else:
    print("Turning right is for loosers, rock falls, you DIE!! Game Over")
