#!/usr/bin/env python

Year = int(input("What year is it? "))

if Year % 4 == 0:
    print("This is a Leap Year")
    if Year % 100 == 0:
        print("This year is not a Leap year")
        if Year % 400 == 0:
            print("This is a Leap Year")
else:
    print("This year is not a Leap year")
